version: "3"
services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./mysql
    ports:
      - "3306:3306"
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "80:80"
 #   depends_on: 
  #    - backend
#  backend:
 #   build:
  #    dockerfile: Dockerfile
   #   context: ./backend
    #ports:
     # - "8080:8080"
   # depends_on:
    #  - db